# Generated by Django 4.0.4 on 2022-05-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('idr', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=100)),
                ('dateDubet', models.DateField()),
                ('dateFin', models.DateField()),
                ('id_Salle', models.IntegerField()),
                ('id_User', models.IntegerField()),
            ],
        ),
    ]
