# Generated by Django 4.0.4 on 2022-05-31 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='id_Salle',
            new_name='Salle',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='dateDubet',
            new_name='dateRES',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='dateFin',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='description',
        ),
        migrations.AddField(
            model_name='reservation',
            name='Houre',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
