# Generated by Django 4.0.4 on 2022-05-31 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_id_salle_reservation_salle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='Houre',
            field=models.TimeField(),
        ),
    ]
