# Generated by Django 4.0.4 on 2022-05-31 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_reservation_salle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='Houre',
            field=models.CharField(max_length=100),
        ),
    ]
