# Generated by Django 4.0.4 on 2022-06-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_reservation_houre'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('idU', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=100)),
                ('Prenom', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=50)),
                ('Filiere', models.CharField(max_length=100)),
                ('Photo', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='idr',
            new_name='idR',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='id_User',
            new_name='idU',
        ),
    ]
