# Generated by Django 4.0.4 on 2022-06-01 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_rename_idr_reservation_idr_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Prefesseur',
        ),
    ]
