# Generated by Django 4.0.4 on 2022-06-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_prefesseur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('idU', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=100)),
                ('Prenom', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=50)),
                ('Filiere', models.CharField(max_length=100)),
                ('Photo', models.ImageField(upload_to=None)),
            ],
        ),
    ]
