# Generated by Django 4.0.4 on 2022-06-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_salle_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='professeur',
            name='role',
            field=models.CharField(default='null', max_length=100),
        ),
    ]
