# Generated by Django 4.0.1 on 2022-06-05 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_remove_professeur_email_professeur_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Professeur',
        ),
        migrations.DeleteModel(
            name='Salle',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='idS',
        ),
        migrations.AddField(
            model_name='reservation',
            name='Type',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
