# Generated by Django 4.0.1 on 2022-06-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_delete_professeur_delete_salle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='Type',
            field=models.CharField(default='Null', max_length=100),
        ),
    ]
