# Generated by Django 4.0.1 on 2022-06-10 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_utilisateur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='email',
            new_name='prenom',
        ),
        migrations.RenameField(
            model_name='utilisateur',
            old_name='password',
            new_name='role',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='username',
        ),
    ]
