# Generated by Django 4.0.1 on 2022-06-12 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_userdata_delete_utilisateurs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserData',
            new_name='Userinfo',
        ),
    ]
