# Generated by Django 4.0.4 on 2022-06-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_delete_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='titre',
            field=models.CharField(default='Null', max_length=100),
        ),
    ]
